//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENU.EJM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobActivity
    {
        public int JobRequestID { get; set; }
        public string JobStatus { get; set; }
        public string Description { get; set; }
        public string EngineerID { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual tblEngineer tblEngineer { get; set; }
        public virtual tblJobRequest tblJobRequest { get; set; }
    }
}
